sources:
  - name: raw_commit_comments
    path: quary-analytics.airbyte_github.commit_comments
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: author_association
      - name: body
      - name: commit_id
      - name: created_at
      - name: html_url
      - name: id
      - name: line
      - name: node_id
      - name: path
      - name: position
      - name: reactions
      - name: repository
      - name: updated_at
      - name: url
      - name: user
  - name: raw_comments
    path: quary-analytics.airbyte_github.comments
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: author_association
      - name: body
      - name: created_at
      - name: html_url
      - name: id
      - name: issue_url
      - name: node_id
      - name: performed_via_github_app
      - name: reactions
      - name: repository
      - name: updated_at
      - name: url
      - name: user
      - name: user_id
  - name: raw_contributor_activity
    path: quary-analytics.airbyte_github.contributor_activity
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: avatar_url
      - name: email
      - name: events_url
      - name: followers_url
      - name: following_url
      - name: gists_url
      - name: gravatar_id
      - name: html_url
      - name: id
      - name: login
      - name: name
      - name: node_id
      - name: organizations_url
      - name: received_events_url
      - name: repos_url
      - name: repository
      - name: site_admin
      - name: starred_at
      - name: starred_url
      - name: subscriptions_url
      - name: total
      - name: type
      - name: url
      - name: weeks
  - name: raw_contributor_activity_airbyte_tmp
    path: quary-analytics.airbyte_github.contributor_activity_airbyte_tmp
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: avatar_url
      - name: email
      - name: events_url
      - name: followers_url
      - name: following_url
      - name: gists_url
      - name: gravatar_id
      - name: html_url
      - name: id
      - name: login
      - name: name
      - name: node_id
      - name: organizations_url
      - name: received_events_url
      - name: repos_url
      - name: repository
      - name: site_admin
      - name: starred_at
      - name: starred_url
      - name: subscriptions_url
      - name: total
      - name: type
      - name: url
      - name: weeks
  - name: raw_pull_request_stats
    path: quary-analytics.airbyte_github.pull_request_stats
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: additions
      - name: can_be_rebased
      - name: changed_files
      - name: comments
      - name: commits
      - name: deletions
      - name: id
      - name: maintainer_can_modify
      - name: merge_state_status
      - name: mergeable
      - name: merged
      - name: merged_by
      - name: node_id
      - name: number
      - name: repository
      - name: review_comments
      - name: updated_at
  - name: raw_pull_requests
    path: quary-analytics.airbyte_github.pull_requests
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: _links
      - name: active_lock_reason
      - name: assignee
      - name: assignees
      - name: author_association
      - name: auto_merge
      - name: base
      - name: body
      - name: closed_at
      - name: comments_url
      - name: commits_url
      - name: created_at
      - name: diff_url
      - name: draft
      - name: head
      - name: html_url
      - name: id
      - name: issue_url
      - name: labels
      - name: locked
      - name: merge_commit_sha
      - name: merged_at
      - name: milestone
      - name: node_id
      - name: number
      - name: patch_url
      - name: repository
      - name: requested_reviewers
      - name: requested_teams
      - name: review_comment_url
      - name: review_comments_url
      - name: state
      - name: statuses_url
      - name: title
      - name: updated_at
      - name: url
      - name: user
  - name: raw_releases
    path: quary-analytics.airbyte_github.releases
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: assets
      - name: assets_url
      - name: author
      - name: body
      - name: body_html
      - name: body_text
      - name: created_at
      - name: discussion_url
      - name: draft
      - name: html_url
      - name: id
      - name: mentions_count
      - name: name
      - name: node_id
      - name: prerelease
      - name: published_at
      - name: reactions
      - name: repository
      - name: tag_name
      - name: tarball_url
      - name: target_commitish
      - name: upload_url
      - name: url
      - name: zipball_url
  - name: raw_repositories
    path: quary-analytics.airbyte_github.repositories
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: allow_forking
      - name: archive_url
      - name: archived
      - name: assignees_url
      - name: blobs_url
      - name: branches_url
      - name: clone_url
      - name: collaborators_url
      - name: comments_url
      - name: commits_url
      - name: compare_url
      - name: contents_url
      - name: contributors_url
      - name: created_at
      - name: default_branch
      - name: deployments_url
      - name: description
      - name: disabled
      - name: downloads_url
      - name: events_url
      - name: fork
      - name: forks
      - name: forks_count
      - name: forks_url
      - name: full_name
      - name: git_commits_url
      - name: git_refs_url
      - name: git_tags_url
      - name: git_url
      - name: has_discussions
      - name: has_downloads
      - name: has_issues
      - name: has_pages
      - name: has_projects
      - name: has_wiki
      - name: homepage
      - name: hooks_url
      - name: html_url
      - name: id
      - name: is_template
      - name: issue_comment_url
      - name: issue_events_url
      - name: issues_url
      - name: keys_url
      - name: labels_url
      - name: language
      - name: languages_url
      - name: license
      - name: merges_url
      - name: milestones_url
      - name: mirror_url
      - name: name
      - name: node_id
      - name: notifications_url
      - name: open_issues
      - name: open_issues_count
      - name: organization
      - name: owner
      - name: permissions
      - name: private
      - name: pulls_url
      - name: pushed_at
      - name: releases_url
      - name: security_and_analysis
      - name: size
      - name: ssh_url
      - name: stargazers_count
      - name: stargazers_url
      - name: statuses_url
      - name: subscribers_url
      - name: subscription_url
      - name: svn_url
      - name: tags_url
      - name: teams_url
      - name: topics
      - name: trees_url
      - name: updated_at
      - name: url
      - name: visibility
      - name: watchers
      - name: watchers_count
      - name: web_commit_signoff_required
  - name: raw_review_comments
    path: quary-analytics.airbyte_github.review_comments
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: _links
      - name: author_association
      - name: body
      - name: commit_id
      - name: created_at
      - name: diff_hunk
      - name: html_url
      - name: id
      - name: in_reply_to_id
      - name: line
      - name: node_id
      - name: original_commit_id
      - name: original_line
      - name: original_position
      - name: original_start_line
      - name: path
      - name: position
      - name: pull_request_review_id
      - name: pull_request_url
      - name: reactions
      - name: repository
      - name: side
      - name: start_line
      - name: start_side
      - name: subject_type
      - name: updated_at
      - name: url
      - name: user
  - name: raw_users
    path: quary-analytics.airbyte_github.users
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: avatar_url
      - name: events_url
      - name: followers_url
      - name: following_url
      - name: gists_url
      - name: gravatar_id
      - name: html_url
      - name: id
      - name: login
      - name: node_id
      - name: organization
      - name: organizations_url
      - name: received_events_url
      - name: repos_url
      - name: site_admin
      - name: starred_url
      - name: subscriptions_url
      - name: type
      - name: url
  - name: raw_workflow_jobs
    path: quary-analytics.airbyte_github.workflow_jobs
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: check_run_url
      - name: completed_at
      - name: conclusion
      - name: created_at
      - name: head_branch
      - name: head_sha
      - name: html_url
      - name: id
      - name: labels
      - name: name
      - name: node_id
      - name: repository
      - name: run_attempt
      - name: run_id
      - name: run_url
      - name: runner_group_id
      - name: runner_group_name
      - name: runner_id
      - name: runner_name
      - name: started_at
      - name: status
      - name: steps
      - name: url
      - name: workflow_name
  - name: raw_workflow_runs
    path: quary-analytics.airbyte_github.workflow_runs
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: actor
      - name: artifacts_url
      - name: cancel_url
      - name: check_suite_id
      - name: check_suite_node_id
      - name: check_suite_url
      - name: conclusion
      - name: created_at
      - name: display_title
      - name: event
      - name: head_branch
      - name: head_commit
      - name: head_repository
      - name: head_sha
      - name: html_url
      - name: id
      - name: jobs_url
      - name: logs_url
      - name: name
      - name: node_id
      - name: path
      - name: previous_attempt_url
      - name: pull_requests
      - name: referenced_workflows
      - name: repository
      - name: rerun_url
      - name: run_attempt
      - name: run_number
      - name: run_started_at
      - name: status
      - name: triggering_actor
      - name: updated_at
      - name: url
      - name: workflow_id
      - name: workflow_url
  - name: raw_workflows
    path: quary-analytics.airbyte_github.workflows
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: badge_url
      - name: created_at
      - name: html_url
      - name: id
      - name: name
      - name: node_id
      - name: path
      - name: repository
      - name: state
      - name: updated_at
      - name: url
  - name: raw_commits
    path: quary-analytics.airbyte_github.commits
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: author
      - name: branch
      - name: comments_url
      - name: commit
      - name: committer
      - name: created_at
      - name: html_url
      - name: node_id
      - name: parents
      - name: repository
      - name: sha
      - name: url
models:
  - name: stg_workflow_runs
    description: Staging table defining the GitHub Actions workflow runs, detailing each run's initiation, completion, status, and outcome within the organisation's CI/CD process.
    columns:
      - name: id
        description: The unique identifier for each Github Actions workflow run.
        tests:
          - type: not_null
      - name: created_at
        description: The timestamp when the workflow run was initiated
      - name: updated_at
        description: The timestamp of the last update to the workflow run.
      - name: status
        description: The current status for the workflow run.
      - name: conclusion
        description: The outcome of the workflow run.
      - name: event
        description: The type of event that triggered the workflow run.
      - name: head_branch
        description: The name of the branch that triggered the workflow run.
      - name: repository_name
        description: The name of the GitHub repository associated with the workflow run.
      - name: actor_login
        description: " The GitHub username of the individual or bot that initiated the workflow run."
      - name: workflow_id
        description: "A unique identifier for the specific GitHub Actions workflow that was executed. "
      - name: head_commit_id
        description: The unique identifier (SHA) of the most recent commit in the branch at the time the workflow run was triggered.
      - name: head_commit_timestamp
        description: ": The timestamp of the most recent commit that triggered the workflow run, providing a precise moment when the code changes were made. "
  - name: stg_pull_requests
    description: Raw Pull Requests coming from Github.
    columns:
      - name: id
        description: The pull request identifier.
        tests:
          - type: unique
          - type: not_null
      - name: state
        description: The pull request state, either closed or open.
        tests:
          - type: accepted_values
            info:
              values: closed,open
      - name: title
        description: The pull request title.
      - name: created_at
        description: The time the pull request was created.
      - name: updated_at
        description: The time the pull request was last updated.
      - name: closed_at
        description: The time the pull request was closed.
      - name: merged_at
        description: The time the pull request was merged.
      - name: repository
        description: The pull request repository.
      - name: author
        description: The author of the pull request.
  - name: stg_commits
    description: Replace this with your description for commits
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: author
      - name: branch
      - name: comments_url
      - name: commit
      - name: committer
      - name: created_at
      - name: html_url
      - name: node_id
      - name: parents
      - name: repository
      - name: sha
      - name: url
